# For MongoDB use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    container_name: database-mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: sigadatabse
    ports:
      - "27017:27017"
    volumes:
      - "./database-scripts:/database-scripts"

  app:
    build:
      context: ./api/api-login
      dockerfile: Dockerfile
    container_name: api-login
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - "3000:3000"
    volumes:
      - ./api/api-login:/home/node/app
    tty: true
    depends_on:
      - mongo