@startuml
scale 2
skinparam PackageStyle rect

title SigaMobile Model Classes
' em sexo true é masculino e false é feminino
class People{
    + _id: ObjectID
    + nome: String
    + nascimento: UTCDateTime
    + rg: String
    + cpf: String
    + sexo: Boolean
    + estCivil: String
    + naturaliade: String
    + raca: String
    + fatorRh: String
    + email: String
    + contaBancoId: ObjectID
    + enderecoId: ObjectID
}

class ContaBanco{
    + _id: ObjectID
    + numConta: String
    + agConta: String
    + operacao: String
    + instituicao: String
}

class Endereco{
    + _id: ObjectID
    + logradouro: String
    + numero: Integer
    + bairro: String
    + cidade: String
    + estado: String
    + cep: Integer
    + complemento: String
}

class Telefone{
    + _id: ObjectID
    + tipo: String
    + numero: Integer
}

class Studant{
    + _id: ObjectID
    + registration: Integer
    + peopleId: ObjectID
    + cursoId: ObjectID
}

class Professor{
    + _id: ObjectID
    + pessoaId: ObejectID
    + coordena: Boolean
}

' tipo pode ser Graduação, Técnico, Ensino Médio, etc...
class Curso{
    + _id: ObjectID
    + nome: String
    + tipo: String
    + coordenadorId: ObjectID
}

' aqui Turma é igual a Disciplina
class Turma{
    + _id: ObjectID
    + nome: String
    + professorId: ObjectID
    + cursoId: ObjectID
}

' aqui tipo_nota é AV1, AV2 e PF
class NotaAluno{
    + _id: ObejectID
    + alunoId: ObjectID
    + turmaId: ObejectID
    + nota: Float
    + tipoNota: String
}

class HorarioTurma{
    + _id: ObejectID
    + turma_id: ObejectID
    + horaInicio: String
    + horaFinal: String
}

class TarefaTurma{
    + _id: ObjectID
    + turmaId: ObejectID
    + descricao: String
    + createdAt: UTCDataTime
    + updatedAt: UTCDataTime
    + finishAt: UTCDataTime
}

class StudantTask{
    + _id: ObjectID
    + descricao: String
    + completed: Boolean
    + fileUri: String
    + studantId: ObejectID
    + createdAt: UTCDataTime
    + updatedAt: UTCDataTime
}

Studant -down-> People
Professor -down-> People

People "1" *-right- "1" ContaBanco: contains
People "1" *-left- "1" Endereco: contains
People "1" *-down- "many" Telefone: contains
Professor "1" *-right- "many" Turma: contains
Studant "many" *-left- "many" Turma: contains
Studant "1" *-up- "many" NotaAluno: contains
Studant "1" *-up- "many" StudantTask: contains
Studant "1" *-up- "many" HorarioTurma: contains
Turma "1" *-up- "many" TarefaTurma: contains
Curso "many" *-left- "many" Studant: contains

newpage
title SigaMobile Controllers
class LoginController{

}

class HistoricoEscolarController{

}

class DadosPessoaisController{

}

class AlunoNotasController{

}


@enduml